struct vIn {
	float4 color    : COLOR;
	float4 position : POSITION;
};

struct vOut {
	float4 col : COLOR;
	float4 pos : POSITION;
};

vOut main(
	vIn              I,
	uniform float4x4 m_model,
	uniform float4x4 m_view,
	uniform float4x4 m_proj
	)
{
	vOut   result;

	float4 pos;
	pos = mul(float4(I.position.xyz, 1.0), m_model);
	pos = mul(pos, m_view);
	pos = mul(pos, m_proj);
	pos.xyz = pos.xyz / pos.w;

	result.col = I.color;
	result.pos = pos;
	return result;
}
